[package]
name = "egui"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.12"
egui_glium = "0.12"
epi = "0.12"
im-native-dialog = { path = "../../" }